### ISSUE TITLE
Transmit power 2.4GHz and 5GHz

### ISSUE THREAD

**Issue by HavingaThijs** [MicroPhase/antsdr-fw#10]
I am using the ANTSDR E310 with [openwifi](https://github.com/open-sdr/openwifi). According to the [system_top.v](https://github.com/open-sdr/openwifi-hw/blob/master/boards/antsdr/src/system_top.v), it is configured for frequencies of 3-6GHz, but the Tx power I measure at 2.4GHz (WiFi channel 6) is even 3dB higher than at 5GHz (channel 44). Do you have an explanation for this?

**Comment by black-pigeon** [comment]
This maybe cuased by the different balun before the signal went into rf switch. The balun for high/low frequency is not the same, the balun at lower frequency have a better performance.

**Comment by JiaoXianjun** [comment]
Thanks. Could you share us the frequency response (insertion loss) figure of the balun? Or is there a datasheet?

**Comment by black-pigeon** [comment]
Sure, here are these datasheets [BD3150L50100A](https://www.richardsonrfpd.com/docs/rfpd/BD3150L50100A00%20Data%20sheet%20Rev%20C.pdf)and [TC1-1-13M+](https://www.minicircuits.com/pdfs/TC1-1-13M+.pdf). 

**Note:** TC1-1-13M+ is not the unit mounted on the antsdr PCB, but has similar performance.

**Comment by HavingaThijs** [comment]
Thanks for sharing the datasheets. It explains the observation.
