### ISSUE TITLE
Load bitstream from HW manager

### ISSUE THREAD

**Issue by qarlosalberto** [MicroPhase/antsdr-fw#13]
I want to load a custom bitstream from HW Manager, do I need to do anything before or after load it? (as change a jumper, execute a command...)

**Comment by black-pigeon** [comment]
Did you build your baremental application?  If so, you can just download the bitstream into the device through HW manager. However, if you want to change the bitstream of the image, I would recommand you create a BOOT.bin(FSBL+bitstream+uboot.elf), and then replace the BOOT.bin in the SD card.

**Comment by qarlosalberto** [comment]
I have build the antsdr project from the repository (without modifications). I have added 4 signals to the ILA:

- adc_valid, adc_enable and adc_data
- A constant.

I can see the constant in the ILA, but not the ADC signals. I think that the problem with the ADC signals is related to the clock. Do I need to execute any command after to load the bitstream from the HW manager?

I have executed this simple program. It works fine after power-on the board, but it fails after to load the bitstream:

```
#include <stdio.h>
#include <iio.h>
#include <stdint.h>
 
unsigned BUFFER_SIZE = 2000;
unsigned NUM_OF_TESTS = 10;

int receive(struct iio_context *ctx)
{
	struct iio_device *dev;
	struct iio_channel *rx0_i, *rx0_q;
	struct iio_buffer *rxbuf;
 
	dev = iio_context_find_device(ctx, "cf-ad9361-lpc");
 
	rx0_i = iio_device_find_channel(dev, "voltage0", 0);
	rx0_q = iio_device_find_channel(dev, "voltage1", 0);
 
	iio_channel_enable(rx0_i);
	iio_channel_enable(rx0_q);
 
	rxbuf = iio_device_create_buffer(dev, BUFFER_SIZE, false);
	if (!rxbuf) {
		// perror("Could not create RX buffer");
		// shutdown();
	}
 
	uint64_t timestamp_last = 0;
	uint64_t timestamp      = 0;
	uint64_t timestamp_dif  = 0;

	for (size_t j = 0; j < NUM_OF_TESTS; j++){

	// while (true) {
		void *p_dat, *p_end, *t_dat;
		ptrdiff_t p_inc;
 
		iio_buffer_refill(rxbuf);
 
		p_inc = iio_buffer_step(rxbuf);
		p_end = iio_buffer_end(rxbuf);
		p_dat = iio_buffer_first(rxbuf, rx0_i);

		for (int index=0; index < 10; p_dat += p_inc, t_dat += p_inc, ++index) {

			const uint16_t i = ((uint16_t*)p_dat)[0]; // Real (I)
			const uint16_t q = ((uint16_t*)p_dat)[1]; // Imag (Q)
 
			printf("%#x\n", i);
			printf("%#x\n", q);
		}
		printf("****************************************************************************************\n");
	}
	iio_buffer_destroy(rxbuf); 
}


int main (int argc, char **argv)
{
	struct iio_context *ctx;
	struct iio_device *phy;
 
 	ctx = iio_create_context_from_uri("ip:10.12.1.201");
 
 
	phy = iio_context_find_device(ctx, "ad9361-phy");
 
	iio_channel_attr_write_longlong(
		iio_device_find_channel(phy, "altvoltage0", true),
		"frequency",
		2400000000); /* RX LO frequency 2.4GHz */
 
	iio_channel_attr_write_longlong(
		iio_device_find_channel(phy, "voltage0", false),
		"sampling_frequency",
 		1920000); 

	iio_device_set_kernel_buffers_count(phy, 16);
	receive(ctx);
 
	iio_context_destroy(ctx);
 
	return 0;
} 

```

With the error:

```
ERROR: READ LINE: -32
ERROR: Open unlocked: -32
Segmentation fault (core dumped)
```

Again I suspect that it's a problem with the ADC clock. What am I doing bad?

**Comment by MicroPhase** [comment]
When you load your bitstream onto the board by HW manager, the system is dump, and the linux on the antsdr will not work.

In that case, you should create a BOOT.bin instead of loading the bitstream directly to the board. To Create a BOOT.bin file, you will need a fsbl.elf, your new design fpga bitstream, and the uboot.elf of the antsdr project. 

Yuo can find the fsbl.elf and uboot.elf after you build the project from source.

You can refer to the Makefile to create a BOOT.bin(or let's say the boot images)

https://github.com/MicroPhase/antsdr-fw/blob/b18fbfde6f615dbb02131ef8c9caf10a18a473ad/Makefile#L202-L219

**Comment by qarlosalberto** [comment]
When I do de make I have the error:

```
  GEN      sys/time.h
  GEN      sys/stat.h
  GEN      sys/wait.h
  GEN      unistd.h
  GEN      wchar.h
  GEN      wctype.h
/usr/bin/make  all-am
  CC       gl_avltree_oset.o
  CC       binary-io.o
  CC       c-ctype.o
  CC       c-stack.o
  CC       c-strcasecmp.o
  CC       c-strncasecmp.o
  CC       clean-temp.o
  CC       cloexec.o
  CC       close-stream.o
  CC       closein.o
  CC       closeout.o
  CC       dirname.o
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
  CC       basename.o
make[6]: *** [Makefile:1915: c-stack.o] Error 1
make[6]: *** Waiting for unfinished jobs....
  CC       dirname-lgpl.o
make[5]: *** [Makefile:1674: all] Error 2
make[4]: *** [Makefile:1572: all-recursive] Error 1
make[3]: *** [Makefile:1528: all] Error 2
make[2]: *** [package/pkg-generic.mk:269: /home/carlos/Downloads/pepe2/antsdr-fw/buildroot/output/build/host-m4-1.4.18/.stamp_built] Error 2
make[1]: *** [Makefile:84: _all] Error 2
make[1]: Leaving directory '/home/carlos/Downloads/pepe2/antsdr-fw/buildroot'
make: *** [Makefile:128: buildroot/output/images/rootfs.cpio.gz] Error 2
```

**Comment by qarlosalberto** [comment]
Or could you share the current fsbl.elf and uboot.elf? As I'm not changing the device tree I think what I can use the same files.

**Comment by MicroPhase** [comment]
Hello, we create a release, you can find the uboot.elf and the fsbl here. 

There is some error when compile the firmware from source because of the chinese character, we have fixed it.

By the way, you can find the uboot.elf, and fsbl once you build the firmware from scratch. These files will be stored in the **build** folder.

When you add ILA to the vivado design, you can export a new hdf(hardware description), and you can create a new BOOT.bin, replace the BOOT.bin and power on the antsdr, then you can add the itx file in the vivado, finally you will get the ILA debug window.

**Comment by qarlosalberto** [comment]
Thank you very much!!

**Comment by qarlosalberto** [comment]
Is there a easy way to change the static IP for eth0 interface permanently?

**Comment by qarlosalberto** [comment]
Thanks! You can close the issue :)
