### ISSUE TITLE
Low sample rates

### ISSUE THREAD

**Issue by qarlosalberto** [MicroPhase/antsdr-fw#14]
I want to use a sample rate of 1.92 Mhz. Is it possible or do I need to configure the FPGA FIR decimator?

**Comment by MicroPhase** [comment]
The default plutosdr based firmware has ddc/duc chain, the FIR using 8x interpolation and decimation. 
You can use sample rate 1.92MHz, the lowest sample rate could be 200KHz.

**Comment by qarlosalberto** [comment]
ok, thanks!
